:recycle: Refactor the installation script

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -195,7 +195,7 @@ function install_homebrew_packages() {
   readonly formulae=(
     "act" "azure-cli" "cmatrix" "exa" "fd" "gcc" "gh" "glow" "httpie" "htop"
     "lua@5.1" "mdbook" "neofetch" "neovim" "poetry" "pre-commit" "ripgrep"
-    "starship" "tmux" "shellcheck" "stow" "zsh"
+    "rustup-init" "starship" "tmux" "shellcheck" "stow" "zsh"
   )
 
   # Install some of the Homebrew taps
@@ -318,6 +318,22 @@ function setup_rust() {
   echo "Hello World!"
 }
 
+#####################################################################
+# Download and setup Node.js for frontend development.
+#
+# Arguments:
+#   None
+#
+# Outputs:
+#   None
+#####################################################################
+function setup_node() {
+  readonly node_download_url="https://deb.nodesource.com/setup_lts.x"
+
+  # Download Node.js
+  curl --silent --show-error --location $node_download_url | bash -c
+}
+
 function setup_gpg() {
   # TODO: Write function to setup the GPG keys to GitHub
   echo "Hello World!"
@@ -331,8 +347,10 @@ function setup_ssh() {
 #####################################################################
 # Entrypoint of the script to invoke with all the arbitrary
 # parameters the script can be invoked with.
+#
 # Arguments:
 #   None
+#
 # Outputs:
 #   None
 #####################################################################
@@ -432,9 +450,17 @@ function main() {
     setup_gh_plugins
   fi
 
+  if ! command -v node &>/dev/null; then
+    info "Installing Node.js..."
+    setup_node
+    success "Node.js installed..."
+  fi
+
   success "Automated system setup complete...please restart the system now!"
 }
 
+# Run the main component of the script to automatically setup everything
 main
 
+# Cleanup any artifacts generated by this script
 trap cleanup EXIT
